modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/woodworks/issues"
license = "https://github.com/team-abnormals/woodworks/blob/main/LICENSE.txt"

[[mods]]
    modId = "woodworks"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "woodworks:sawmill"
    configBackground = "woodworks:textures/block/spruce_boards.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five, hatsondogs"
    displayURL = "https://www.teamabnormals.com/mods/woodworks"
    displayName = "Woodworks"
    description = '''
    Adds very varying wood variant blocks to improve your building capabilities!
    '''

[[dependencies.woodworks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.woodworks]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.woodworks]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.woodworks]]
    modId = "quark"
    mandatory = false
    versionRange = "[0,)"
    ordering = "AFTER"
    side = "BOTH"